import avatar from "./assets/avatar.png";

 const students = [
  {
    id: "c1",
    name: "Class 1",
    students: [
      {
        id: "s10",
        name: "Student c11",
        percentage: "98%",
        avatar: avatar,
        scores: "A+",
      },

      {
        id: "s11",
        name: "Student c12",
        percentage: "78%",
        avatar: avatar,
        scores: "B-",
      },
      {
        id: "s12",
        name: "Student c13",
        percentage: "68%",
        avatar: avatar,
        scores: "C+",
      },
      {
        id: "s13",
        name: "Student c14",
        percentage: "90%",
        avatar: avatar,
        scores: "A",
      },
      {
        id: "s14",
        name: "Student c15",
        percentage: "88%",
        avatar: avatar,
        scores: "A-",
      },
      {
        id: "s15",
        name: "Student c16",
        percentage: "82%",
        avatar: avatar,
        scores: "B",
      },
      {
        id: "s16",
        name: "Student c17",
        percentage: "96%",
        avatar: avatar,
        scores: "A+",
      },
      {
        id: "s17",
        name: "Student c18",
        percentage: "89%",
        avatar: avatar,
        scores: "A-",
      },
      {
        id: "s18",
        name: "Student c19",
        percentage: "90%",
        avatar: avatar,
        scores: "A",
      },
      {
        id: "s19",
        name: "Student c110",
        percentage: "84%",
        avatar: avatar,
        scores: "B+",
      },
    ],
  },
  {
    id: "c2",
    name: "Class 2",
    students: [
      {
        id: "s20",
        name: "Student c21",
        percentage: "98%",
        avatar: avatar,
        scores: "A+",
      },
      {
        id: "s21",
        name: "Student c22",
        percentage: "79%",
        avatar: avatar,
        scores: "B-",
      },
      {
        id: "s22",
        name: "Student c23",
        percentage: "74%",
        avatar: avatar,
        scores: "C+",
      },
      {
        id: "s23",
        name: "Student c24",
        percentage: "92%",
        avatar: avatar,
        scores: "A",
      },
      {
        id: "s24",
        name: "Student c25",
        percentage: "88%",
        avatar: avatar,
        scores: "A-",
      },
      {
        id: "s25",
        name: "Student c26",
        percentage: "83%",
        avatar: avatar,
        scores: "B",
      },
      {
        id: "s26",
        name: "Student c27",
        percentage: "99%",
        avatar: avatar,
        scores: "A+",
      },
      {
        id: "s27",
        name: "Student c28",
        percentage: "93%",
        avatar: avatar,
        scores: "A-",
      },
      {
        id: "s28",
        name: "Student c29",
        percentage: "90%",
        avatar: avatar,
        scores: "A",
      },
      {
        id: "s29",
        name: "Student c210",
        percentage: "87%",
        avatar: avatar,
        scores: "B+",
      },
    ],
  },
  {
    id: "c3",
    name: "Class 4",
    students: [
      {
        id: "s30",
        name: "Student c31",
        percentage: "100%",
        avatar: avatar,
        scores: "A+",
      },
      {
        id: "s31",
        name: "Student c32",
        percentage: "83%",
        avatar: avatar,
        scores: "B-",
      },
      {
        id: "s32",
        name: "Student c33",
        percentage: "77%",
        avatar: avatar,
        scores: "C+",
      },
      {
        id: "s33",
        name: "Student c34",
        percentage: "99.3%",
        avatar: avatar,
        scores: "A",
      },
      {
        id: "s34",
        name: "Student c35",
        percentage: "88%",
        avatar: avatar,
        scores: "A-",
      },
      {
        id: "s35",
        name: "Student c36",
        percentage: "80%",
        avatar: avatar,
        scores: "B",
      },
      {
        id: "s36",
        name: "Student c37",
        percentage: "97%",
        avatar: avatar,
        scores: "A+",
      },
      {
        id: "s37",
        name: "Student c38",
        percentage: "89%",
        avatar: avatar,
        scores: "A-",
      },
      {
        id: "s38",
        name: "Student c39",
        percentage: "91%",
        avatar: avatar,
        scores: "A",
      },
      {
        id: "s39",
        name: "Student c310",
        percentage: "81%",
        avatar: avatar,
        scores: "B+",
      },
    ],
  },
];

export default students;
